// <auto-generated />
using DefineX.Services.ProductAPI.dbcontexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DefineX.Services.ProductAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250327121044_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DefineX.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "YENİ GELEN ÜRÜNLER",
                            Description = "A stylish black dress that combines elegance and comfort. Perfect for both formal and casual occasions.",
                            ImageUrl = "1.png",
                            Name = "Black Dress",
                            Price = 150.0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "TREND",
                            Description = "A beautiful floral blouse that brings a touch of nature to your wardrobe. Light and comfortable for everyday wear.",
                            ImageUrl = "2.png",
                            Name = "Floral Blouse",
                            Price = 130.99000000000001
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "featured products",
                            Description = "A chic white summer dress perfect for sunny days. Made from breathable fabric for maximum comfort.",
                            ImageUrl = "3.png",
                            Name = "White Summer Dress",
                            Price = 100.98999999999999
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "on sale",
                            Description = "A stunning blue cocktail dress that exudes sophistication. Perfect for evening events or special occasions.",
                            ImageUrl = "4.png",
                            Name = "Blue Cocktail Dress",
                            Price = 125.0
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryName = "YENİ GELEN ÜRÜNLER",
                            Description = "A luxurious red silk blouse that adds a touch of glamour to any outfit. Soft and smooth, perfect for evening outings.",
                            ImageUrl = "5.png",
                            Name = "Red Silk Blouse",
                            Price = 135.99000000000001
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryName = "YENİ GELEN ÜRÜNLER",
                            Description = "A cozy grey sweater made with soft fabric. Ideal for colder days, it pairs well with jeans or skirts for a relaxed look.",
                            ImageUrl = "6.png",
                            Name = "Grey Sweater",
                            Price = 120.98999999999999
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryName = "TREND",
                            Description = "A cute pink skirt perfect for warm days. Its light fabric and comfortable fit make it an essential for your summer wardrobe.",
                            ImageUrl = "7.png",
                            Name = "Pink Summer Skirt",
                            Price = 95.5
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryName = "TREND",
                            Description = "A bold black leather jacket that brings an edge to any outfit. Durable and stylish, perfect for cooler seasons.",
                            ImageUrl = "8.png",
                            Name = "Black Leather Jacket",
                            Price = 220.99000000000001
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryName = "featured products",
                            Description = "Light and breathable beige linen pants. Perfect for summer days, offering both comfort and elegance.",
                            ImageUrl = "9.png",
                            Name = "Beige Linen Pants",
                            Price = 110.5
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryName = "featured products",
                            Description = "A versatile black pencil skirt, perfect for both work and formal occasions. Comfortable fit with a professional look.",
                            ImageUrl = "10.png",
                            Name = "Black Pencil Skirt",
                            Price = 95.989999999999995
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryName = "on sale",
                            Description = "A flattering green A-line dress that works well for both casual and formal events. Comfortable and stylish.",
                            ImageUrl = "11.png",
                            Name = "Green A-Line Dress",
                            Price = 135.0
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryName = "on sale",
                            Description = "A classic white blazer that gives your outfit a sophisticated and polished look. Ideal for office wear or evening events.",
                            ImageUrl = "12.png",
                            Name = "White Blazer",
                            Price = 150.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
